refactor
* Remove trailing whitespace
* Convert spaces to tabs

diff --git a/tasks/chromium b/tasks/chromium
--- a/tasks/chromium
+++ b/tasks/chromium
@@ -1,6 +1,6 @@
 prep_install_desktop(){
-    echo "${GREEN}I: Installing Chromium Browser and Patching it${NOATTR}"
-    sudo apt install chromium -yy || :
+	echo "${GREEN}I: Installing Chromium Browser and Patching it${NOATTR}"
+	sudo apt install chromium -yy || :
 }
 
 prep_install_desktop
@@ -10,8 +10,8 @@ sudo dpkg --configure -a
 
 # Check if dependencies installed
 if [ ! -e "$(command -v chromium)" ]; then
-    echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
-    exit 2
+	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+	exit 2
 fi
 
 # Patch Chromium
diff --git a/tasks/cli-extras b/tasks/cli-extras
--- a/tasks/cli-extras
+++ b/tasks/cli-extras
@@ -1,6 +1,6 @@
 prep_install_desktop(){
-    echo "${GREEN}I: Installing the CLI Extras needed for your CLI needs and some recommended tools that is used by me${NOATTR}"
-    sudo apt install nmap git wget byobu zsh fish nano htop qemu-system-x86 lynx man rsync openssh-client openssh-server vim emacs tor -yy || :
+	echo "${GREEN}I: Installing the CLI Extras needed for your CLI needs and some recommended tools that is used by me${NOATTR}"
+	sudo apt install nmap git wget byobu zsh fish nano htop qemu-system-x86 lynx man rsync openssh-client openssh-server vim emacs tor -yy || :
 }
 
 prep_install_desktop
@@ -14,8 +14,8 @@ for d in /usr/bin/{nmap,git,wget,byobu,fish,nano,htop,qemu-system-i386,lynx,man,
 }
 
 if ! check_deps; then
-    echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
-    exit 2
+	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+	exit 2
 fi
 
 echo "${GREEN}I: Successfully Installed ${YELLOW}cli-extras${GREEN} Packages include for Web Browsing, Network Scanning, SSH, Editors, Emulators, and Git${NOATTR}"
diff --git a/tasks/i3wm b/tasks/i3wm
--- a/tasks/i3wm
+++ b/tasks/i3wm
@@ -1,6 +1,6 @@
 prep_install_desktop(){
-    echo "${GREEN}I: Installing the Basic i3 Window Manager Package, This may take some time${NOATTR}"
-    sudo apt install i3 rofi feh xfce4-terminal dbus-x11 pcmanfm firefox-esr tigervnc-standalone-server tigervnc-xorg-extension -yy || :
+	echo "${GREEN}I: Installing the Basic i3 Window Manager Package, This may take some time${NOATTR}"
+	sudo apt install i3 rofi feh xfce4-terminal dbus-x11 pcmanfm firefox-esr tigervnc-standalone-server tigervnc-xorg-extension -yy || :
 }
 
 prep_install_desktop
@@ -14,8 +14,8 @@ for d in /usr/bin/{firefox,i3,rofi,feh,pcmanfm,dbus-launch,xfce4-terminal,tigerv
 }
 
 if ! check_deps; then
-    echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
-    exit 2
+	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+	exit 2
 fi
 
 # Create Start Script
@@ -24,30 +24,30 @@ cat > /usr/local/bin/starti3wm <<- EOM
 #!/bin/bash
 
 check_lock_files(){
-    for l in /tmp/.X51-lock /tmp/.X11-unix/X51; do test -e "\${l}"; done
+	for l in /tmp/.X51-lock /tmp/.X11-unix/X51; do test -e "\${l}"; done
 }
 
 if check_lock_files; then
-    echo "${RED}E: Another VNC Server is running at port 5951, Please Close it first${NOATTR}"
-    exit 2
+	echo "${RED}E: Another VNC Server is running at port 5951, Please Close it first${NOATTR}"
+	exit 2
 fi
 
 echo "${GREEN}Starting VNC Server with Session: ${YELLOW}i3wm${NOATTR}"
 echo "${GREEN}Running at port ${YELLOW}:51${NOATTR}"
 
 if [ ! -e /var/debdroid/vnc-resolution ]; then
-    set_resolution=\$(
-        dialog --title "Setup VNC Resolution" \
-            --inputbox "Enter your Resolution for your VNC Display (WxH), You can change settings later, you may leave it blank for defaults" 11 40 \
-            3>&1 1>&2 2>&3 3>&-
-    )
+	set_resolution=\$(
+		dialog --title "Setup VNC Resolution" \
+			--inputbox "Enter your Resolution for your VNC Display (WxH), You can change settings later, you may leave it blank for defaults" 11 40 \
+			3>&1 1>&2 2>&3 3>&-
+	)
 
-    if [ ! -z "\${set_resolution}" ]; then
-        echo "\${set_resolution}" > /var/debdroid/vnc-resolution
-    else
-        echo "${GREEN}I: Using the Default Desired Resolution: ${YELLOW}1280x720${NOATTR}"
-        echo "1280x720" > /var/debdroid/vnc-resolution
-    fi
+	if [ ! -z "\${set_resolution}" ]; then
+		echo "\${set_resolution}" > /var/debdroid/vnc-resolution
+	else
+		echo "${GREEN}I: Using the Default Desired Resolution: ${YELLOW}1280x720${NOATTR}"
+		echo "1280x720" > /var/debdroid/vnc-resolution
+	fi
 fi
 
 echo "${GREEN}Running in the foreground. to terminate it hit Ctrl-C"
