refactor

diff --git a/tasks/cli-development b/tasks/cli-development
--- a/tasks/cli-development
+++ b/tasks/cli-development
@@ -9,14 +9,12 @@ echo "${GREEN}I: Doing Pending Configuration${NOATTR}"
 sudo dpkg --configure -a
 
 # Check if dependencies installed (Base)
-check_deps(){
-for d in /usr/bin/{gcc,make,automake,git,python,vim,cmake,fakeroot}; do test -e ${d}; done
-}
-
-if ! check_deps; then
-	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
-	exit 2
-fi
+for d in gcc make automake git python vim cmake fakeroot; do
+	if command -v ${d} >/dev/null 2>&1; then
+		echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+		exit 2
+	fi
+done
 
 echo "${GREEN}I: Successfully Installed ${YELLOW}cli-developer${GREEN} Packages include for Compiling C Programs, Python, and Make/CMake tools. Other tools must be installed manually${NOATTR}"
 exit 0
diff --git a/tasks/cli-extras b/tasks/cli-extras
--- a/tasks/cli-extras
+++ b/tasks/cli-extras
@@ -9,14 +9,12 @@ echo "${GREEN}I: Doing Pending Configuration${NOATTR}"
 sudo dpkg --configure -a
 
 # Check if dependencies installed (Base)
-check_deps(){
-for d in /usr/bin/{nmap,git,wget,byobu,fish,nano,htop,qemu-system-i386,lynx,man,rsync,ssh,vim,emacs,tor,zsh}; do test -e ${d}; done
-}
-
-if ! check_deps; then
-	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
-	exit 2
-fi
+for d in nmap git wget byobu fish nano htop qemu-system-i386 lynx man rsync ssh vim emacs tor zsh; do
+	if ! command -v ${d} >/dev/null 2>&1; then
+		echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+		exit 2
+	fi
+done
 
 echo "${GREEN}I: Successfully Installed ${YELLOW}cli-extras${GREEN} Packages include for Web Browsing, Network Scanning, SSH, Editors, Emulators, and Git${NOATTR}"
 exit 0
diff --git a/tasks/x11-basic b/tasks/x11-basic
--- a/tasks/x11-basic
+++ b/tasks/x11-basic
@@ -9,9 +9,12 @@ echo "${GREEN}I: Doing Pending Configuration${NOATTR}"
 sudo dpkg --configure -a
 
 # Check if dependencies installed (Base)
-check_deps(){
-for d in /usr/bin/{firefox,openbox-session,feh,pcmanfm,dbus-launch,xfce4-terminal,tigervncserver}; do test -e ${d}; done
-}
+for d in firefox openbox-session feh pcmanfm dbus-launch xfce4-terminal tigervncserver; do
+	if command -v ${d} >/dev/null 2>&1; then
+		echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+		exit 2
+	fi
+done
 
 if ! check_deps; then
 	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
diff --git a/tasks/xfce4-desktop b/tasks/xfce4-desktop
--- a/tasks/xfce4-desktop
+++ b/tasks/xfce4-desktop
@@ -9,9 +9,12 @@ echo "${GREEN}I: Doing Pending Configuration${NOATTR}"
 sudo dpkg --configure -a
 
 # Check if dependencies installed (Base)
-check_deps(){
-for d in /usr/bin/{dbus-launch,firefox,vlc,gimp,libreoffice,xfce4-session,mousepad,xfce4-taskmanager,tigervncserver}; do test -e ${d}; done
-}
+for d in dbus-launch firefox vlc gimp libreoffice xfce4-session mousepad xfce4-taskmanager tigervncserver; do
+	if ! command -v ${d} >/dev/null 2>&1; then
+		echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
+		exit 2
+	fi
+done
 
 if ! check_deps; then
 	echo "${RED}W: An Error Has Occurred during the installation, please try again${NOATTR}"
@@ -60,3 +63,4 @@ chmod 755 /usr/local/bin/startxfce4
 
 echo "${GREEN}I: Successfully Installed ${YELLOW}xfce4-desktop${GREEN}, You can start the session by typing ${YELLOW}startxfce4${NOATTR}"
 exit 0
+
